#version 450

layout(local_size_x = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer CellWeights { uint values[]; } cells;
layout(set = 0, binding = 1, std430) buffer Distances { uint values[]; } distances;
layout(set = 0, binding = 2, std430) buffer PreviousNodes { uint values[]; } previous;
layout(set = 0, binding = 3, std430) buffer VisitedNodes { uint values[]; } visited;
layout(set = 0, binding = 4, std430) buffer DijkstraControl {
    uint minDistance;
    uint selected;
    uint finished;
    uint found;
    uint iterations;
    uint source;
    uint target;
    uint width;
    uint height;
} controlData;

void main() {
    if (controlData.finished == 0u) {
        controlData.minDistance = 0xffffffffu;
        controlData.selected = 0xffffffffu;
    }
}
